
[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#625e4c"
blue = "#9d65ff"
cyan = "#58d1eb"
green = "#98e024"
magenta = "#f4005f"
red = "#f4005f"
white = "#f6f6ef"
yellow = "#e0d561"

[colors.normal]
black = "#1a1a1a"
blue = "#9d65ff"
cyan = "#58d1eb"
green = "#98e024"
magenta = "#f4005f"
red = "#f4005f"
white = "#c4c5b5"
yellow = "#fa8419"

[colors.primary]
background = "0x1a1b26"
foreground = "0xa9b1d6"

[env]
TERM = "xterm-256color"

[font]
size = 18.0

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0


[scrolling]
history = 10000
multiplier = 4

[selection]
save_to_clipboard = true
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>"

[terminal.shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/zsh"

[window.dimensions]
columns = 90
lines = 25

[window.padding]
x = 2
y = 2

[window]
startup_mode = "Maximized"


[general]
# config path: '~/.config/alacritty/alacritty.toml'

live_config_reload = true

[terminal]
